server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}


kafka:
  bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
  admin:
    auto-create: true
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
